/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
/* Header for class com_shadowsong_avhelper_FFMpegUtils */
#include <libavutil/avutil.h>
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#ifndef _Included_com_shadowsong_avhelper_FFMpegUtils
#define _Included_com_shadowsong_avhelper_FFMpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shadowsong_avhelper_FFMpegUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shadowsong_avhelper_FFMpegUtils_getString
  (JNIEnv * env, jclass obj)
    {
        av_register_all();
        
        char wd[512];
        sprintf(wd, "AVCODEC VERSION %u\n"
                , avcodec_version()
                );
        return (*env)->NewStringUTF(env, wd);
    }

#ifdef __cplusplus
}
#endif
#endif
